import type { NaturalEvent, Notification, EmergencyContact, User, ZoneOfInterest } from "./types"

export const mockEvents: NaturalEvent[] = [
  {
    id: "eq-001",
    type: "earthquake",
    name: "Southern California Earthquake",
    location: "Los Angeles, California",
    coordinates: { lat: 34.0522, lng: -118.2437 },
    magnitude: 6.4,
    alertLevel: "critical",
    timestamp: new Date("2026-03-12T08:30:00"),
    description: "A significant earthquake struck the greater Los Angeles area. Multiple aftershocks expected.",
    affectedArea: "Greater Los Angeles Metropolitan Area",
    casualties: 12,
    evacuations: 15000,
    status: "active",
  },
  {
    id: "hr-001",
    type: "hurricane",
    name: "Hurricane Maria",
    location: "Gulf of Mexico",
    coordinates: { lat: 25.7617, lng: -80.1918 },
    category: 4,
    windSpeed: 145,
    alertLevel: "critical",
    timestamp: new Date("2026-03-11T14:00:00"),
    description: "Category 4 hurricane approaching the Florida coast. Expected landfall within 24 hours.",
    affectedArea: "South Florida, Miami-Dade County",
    evacuations: 250000,
    status: "active",
  },
  {
    id: "wf-001",
    type: "wildfire",
    name: "Sierra Nevada Wildfire",
    location: "Fresno County, California",
    coordinates: { lat: 37.0858, lng: -119.4956 },
    acres: 45000,
    alertLevel: "warning",
    timestamp: new Date("2026-03-10T06:00:00"),
    description: "Large wildfire spreading through Sierra Nevada forest. 35% contained.",
    affectedArea: "Sierra National Forest",
    evacuations: 8500,
    status: "active",
  },
  {
    id: "eq-002",
    type: "earthquake",
    name: "Central Mexico Tremor",
    location: "Mexico City, Mexico",
    coordinates: { lat: 19.4326, lng: -99.1332 },
    magnitude: 5.2,
    alertLevel: "moderate",
    timestamp: new Date("2026-03-12T03:15:00"),
    description: "Moderate earthquake felt across Mexico City. Minor structural damage reported.",
    affectedArea: "Mexico City Metropolitan Area",
    status: "monitoring",
  },
  {
    id: "wf-002",
    type: "wildfire",
    name: "Arizona Desert Fire",
    location: "Phoenix, Arizona",
    coordinates: { lat: 33.4484, lng: -112.074 },
    acres: 12000,
    alertLevel: "moderate",
    timestamp: new Date("2026-03-11T18:30:00"),
    description: "Brush fire in the Sonoran Desert. 60% contained.",
    affectedArea: "Tonto National Forest",
    evacuations: 2000,
    status: "monitoring",
  },
  {
    id: "hr-002",
    type: "hurricane",
    name: "Tropical Storm Alex",
    location: "Atlantic Ocean",
    coordinates: { lat: 28.5383, lng: -81.3792 },
    category: 1,
    windSpeed: 85,
    alertLevel: "low",
    timestamp: new Date("2026-03-09T20:00:00"),
    description: "Tropical storm weakening as it moves northeast. Minimal threat to coastal areas.",
    affectedArea: "Central Florida Coast",
    status: "monitoring",
  },
  {
    id: "eq-003",
    type: "earthquake",
    name: "Tokyo Bay Earthquake",
    location: "Tokyo, Japan",
    coordinates: { lat: 35.6762, lng: 139.6503 },
    magnitude: 4.8,
    alertLevel: "low",
    timestamp: new Date("2026-03-11T22:45:00"),
    description: "Minor earthquake in Tokyo Bay area. No damage reported.",
    affectedArea: "Tokyo Metropolitan Area",
    status: "resolved",
  },
  {
    id: "wf-003",
    type: "wildfire",
    name: "Oregon Forest Fire",
    location: "Portland, Oregon",
    coordinates: { lat: 45.5152, lng: -122.6784 },
    acres: 8000,
    alertLevel: "warning",
    timestamp: new Date("2026-03-10T12:00:00"),
    description: "Forest fire in Mount Hood National Forest. 45% contained.",
    affectedArea: "Mount Hood National Forest",
    evacuations: 3500,
    status: "active",
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    eventId: "eq-001",
    type: "alert_increase",
    title: "Alert Level Increased",
    message: "Southern California Earthquake has been upgraded to CRITICAL level. Magnitude increased to 6.4.",
    timestamp: new Date("2026-03-12T08:35:00"),
    read: false,
    alertLevel: "critical",
  },
  {
    id: "notif-002",
    eventId: "hr-001",
    type: "status_change",
    title: "Hurricane Update",
    message: "Hurricane Maria is now Category 4. Expected landfall in 24 hours.",
    timestamp: new Date("2026-03-11T14:30:00"),
    read: false,
    alertLevel: "critical",
  },
  {
    id: "notif-003",
    eventId: "wf-001",
    type: "new_event",
    title: "New Wildfire Detected",
    message: "Sierra Nevada Wildfire has been detected in Fresno County. Current size: 45,000 acres.",
    timestamp: new Date("2026-03-10T06:15:00"),
    read: true,
    alertLevel: "warning",
  },
  {
    id: "notif-004",
    eventId: "eq-002",
    type: "recommendation",
    title: "Safety Recommendation",
    message: "Stay away from damaged buildings. Check for gas leaks. Have emergency supplies ready.",
    timestamp: new Date("2026-03-12T03:20:00"),
    read: true,
    alertLevel: "moderate",
  },
]

export const emergencyContacts: EmergencyContact[] = [
  { id: "ec-001", name: "Emergency Services", phone: "911", type: "emergency", country: "USA" },
  { id: "ec-002", name: "FEMA Disaster Assistance", phone: "1-800-621-3362", type: "government", country: "USA" },
  { id: "ec-003", name: "Red Cross Emergency", phone: "1-800-733-2767", type: "rescue", country: "USA" },
  { id: "ec-004", name: "Poison Control Center", phone: "1-800-222-1222", type: "medical", country: "USA" },
  { id: "ec-005", name: "National Weather Service", phone: "1-800-222-1222", type: "government", country: "USA" },
  { id: "ec-006", name: "Coast Guard Emergency", phone: "1-800-368-5647", type: "rescue", country: "USA" },
]

export const mockZones: ZoneOfInterest[] = [
  {
    id: "zone-001",
    name: "Los Angeles Area",
    coordinates: { lat: 34.0522, lng: -118.2437 },
    radius: 100,
    notifyForTypes: ["earthquake", "wildfire"],
    notifyForAlertLevels: ["critical", "warning"],
  },
  {
    id: "zone-002",
    name: "Miami Region",
    coordinates: { lat: 25.7617, lng: -80.1918 },
    radius: 150,
    notifyForTypes: ["hurricane"],
    notifyForAlertLevels: ["critical", "warning", "moderate"],
  },
]

export const mockUser: User = {
  id: "user-001",
  name: "John Smith",
  email: "john.smith@example.com",
  avatar: undefined,
  zones: mockZones,
  savedEvents: [
    { id: "saved-001", eventId: "eq-001", savedAt: new Date("2026-03-12T09:00:00"), notes: "Monitoring for family in LA" },
    { id: "saved-002", eventId: "hr-001", savedAt: new Date("2026-03-11T15:00:00") },
  ],
  preferences: {
    notifications: true,
    emailAlerts: true,
    smsAlerts: false,
  },
}

export const preventionRecommendations = {
  earthquake: [
    "Secure heavy furniture and appliances to walls",
    "Create an emergency supply kit with water, food, and first aid",
    "Identify safe spots in each room (under sturdy tables, against interior walls)",
    "Know how to shut off gas, water, and electricity",
    "Practice drop, cover, and hold on drills",
    "Keep shoes and flashlight near your bed",
  ],
  hurricane: [
    "Board up windows and secure outdoor furniture",
    "Stock up on water (1 gallon per person per day for 3 days)",
    "Fill your car with gas and have cash ready",
    "Know your evacuation zone and routes",
    "Charge all electronic devices before the storm",
    "Document your property with photos for insurance",
  ],
  wildfire: [
    "Create a defensible space around your home (30-100 feet)",
    "Clear dry vegetation, leaves, and debris from roof and gutters",
    "Have a go-bag ready with important documents",
    "Know multiple evacuation routes from your area",
    "Keep emergency supplies in your car",
    "Sign up for local emergency alerts",
  ],
}
